### PR TITLE
update event dispatch

### PR DESCRIPTION
**Pull request by ffreyer**
For https://github.com/JuliaPlots/AbstractPlotting.jl/pull/634

This generates the right events as far as I can tell, though there's some weirdness in 3D plots. Scrolling and panning doesn't work correctly. Also selection rectangles don't show up. Though I think this may have been the case before?

There may also be a better way to do this from JS, but I don't know how.

### CODE REVIEW

**Comment by SimonDanisch** [comment]
>Also selection rectangles don't show up.

Hm, that's new... 

>Scrolling and panning doesn't work correctl

That is not ^^

**Comment by ffreyer** [comment]
We should get this merged so WGLMakie is compatible with the next AbstractPlotting release. Writing to `mousebuttons` and `keyboardbuttons` won't work anymore...

**Comment by ffreyer** [comment]
I checked again...
* 3d zooming, rotation works
* 3d panning doesn't, it rotates instead... (even though it correctly identifies the right mouse button and the left one is not seen as active by AbstractPlotting)
* 2d selection rectangle works

**Comment by SimonDanisch** [comment]
Thanks :)

**Pull request merged**
