### PR TITLE
[WIP] Use deps/build.jl to add unregistered dependencies

### PR DESCRIPTION
**Pull request by asinghvi17**

### CODE REVIEW

**Comment by asinghvi17** [comment]
Well, that was an interesting dive into Pkg.  Thankfully the docs are decent!

**Comment by asinghvi17** [comment]
Since with this PR the build process will be automated, I will enable Travis on the repo when it's merged (for that sweet green badge :))

**Comment by asinghvi17** [comment]
It looks like this installs the deps to a temp environment, so that won't be too helpful.

**Comment by SimonDanisch** [comment]
Thanks for this, but JSCall got registered some time ago ;) :-P

**Comment by asinghvi17** [comment]
Nice, it's just ShaderAbstractions then? 

Also, this doesn't work quite right - Pkg switches you to a temporary environment in the build stage so you can't use it to build.  I could try switching environments internally but I don't know if that would mess anything up.

**Comment by asinghvi17** [comment]
I'll close this, and make another PR to add ShaderAbstractions manually when testing - that should fix the problem for now.

**Pull request closed without merging**
